In [1]:
# CONCLUSION

# Model Scores = accuracy on training dataset (100% may overfit though?)
# Random Forest ---------------> 100.00
# Decision Tree ---------------> 100.00
# Support Vector Machines -----> 76.17
# Linear SVC ------------------> 69.42
# Logistic Regression ---------> 67.73
# Stochastic Gradient Decent --> 63.04
# KNN -------------------------> 61.16
# Naive Bayes -----------------> 60.79
# Perceptron ------------------> 57.60

In [2]:
# DataFrame
import pandas as pd
import numpy as np

# ML Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

# Train Test Split
from sklearn import model_selection

# Feature Scaling
from sklearn.preprocessing import StandardScaler

# Model Evaluation
from sklearn.metrics import classification_report, confusion_matrix

# Visualization
import matplotlib.pyplot as plt

In [3]:
FIRST_YEAR = 2000
CURRENT_YEAR = 2021

In [4]:
df = pd.read_csv(str(FIRST_YEAR) + '-' + str(CURRENT_YEAR) + ' Train Dataset.csv', encoding='utf-8')
df

Position  Pick  Team PF  Team Yds  Team Tot Yds & TOPly  \
0           1     1    279.0    5169.0                1049.0   
1           2     2    266.0    4395.0                 885.0   
2           2     3    341.0    5549.0                1021.0   
3           1     4    341.0    5416.0                1012.0   
4           1     5    306.0    4960.0                1022.0   
..        ...   ...      ...       ...                   ...   
662         1    27    308.0    4752.0                 999.0   
663         2    28    423.0    5726.0                 979.0   
664         1    29    396.0    5586.0                1085.0   
665         2    30    392.0    5296.0                1011.0   
666         1    31    526.0    6412.0                 994.0   

     Team Tot Yds & TOY/P  Team Tot Yds & TOTO  Team FL  Team 1stD  \
0                     4.9                 30.0     14.0      312.0   
1                     5.0                 21.0      8.0      248.0   
2                     5.4                 23.0      8.0      313.0   
3                     5.4                 33.0     16.0      311.0   
4                     4.9                 26.0      8.0      315.0   
..                    ...                  ...      ...        ...   
662                   4.8                 22.0      6.0      268.0   
663                   5.8                 28.0     11.0      327.0   
664                   5.1                 18.0      7.0      331.0   
665                   5.2                 22.0      9.0      294.0   
666                   6.5                 31.0     16.0      335.0   

     Team PassingCmp  ...  Def. Rank RushingYds  Def. Rank RushingTD  \
0              356.0  ...                  32.0                 27.0   
1              298.0  ...                  31.0                 17.0   
2              344.0  ...                  21.0                 14.0   
3              376.0  ...                  20.0                 28.0   
4              371.0  ...                  27.0                 21.0   
..               ...  ...                   ...                  ...   
662            272.0  ...                  17.0                 25.0   
663            338.0  ...                  18.0                 18.0   
664            320.0  ...                   7.0                  2.0   
665            304.0  ...                  10.0                  7.0   
666            343.0  ...                   1.0                  1.0   

     Def. Rank RushingY/A  Def. Rank Sc%  Def. Rank TO%  \
0                    25.0            9.0           27.0   
1                    26.0            4.0           15.0   
2                    10.0            7.0           25.0   
3                     4.0            8.0           29.0   
4                    22.0            1.0           28.0   
..                    ...            ...            ...   
662                  20.0           12.0            6.0   
663                  26.0            8.0           27.0   
664                  14.0           30.0           14.0   
665                  22.0           26.0            4.0   
666                   6.0           28.0            8.0   

     Def. Rank Average DriveStart  Def. Rank Average DriveTime  \
0                            12.0                         18.0   
1                            31.0                         31.0   
2                             3.0                         21.0   
3                            25.0                         19.0   
4                            27.0                         20.0   
..                            ...                          ...   
662                           4.0                         13.0   
663                          14.0                         24.0   
664                           1.0                          9.0   
665                           2.0                          6.0   
666                           9.0                          3.0   

     Def. Rank Average Drive

In [5]:
# Train Test Split
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(df.drop('Position', axis=1), df['Position'], 
                                                                    test_size = 0.2, stratify = df['Position'], random_state=42)

In [6]:
X_train

Pick  Team PF  Team Yds  Team Tot Yds & TOPly  Team Tot Yds & TOY/P  \
371    21    232.0    3985.0                 921.0                   4.3   
657    22    338.0    4805.0                 971.0                   4.9   
518     9    276.0    5358.0                1024.0                   5.2   
197     7    288.0    4432.0                 981.0                   4.5   
5       6    337.0    5879.0                 997.0                   5.9   
..    ...      ...       ...                   ...                   ...   
85     22    334.0    5024.0                 974.0                   5.2   
88     25    395.0    4886.0                1054.0                   4.6   
584    12    295.0    4898.0                 955.0                   5.1   
145    18    333.0    5142.0                1052.0                   4.9   
500    23    320.0    5153.0                 939.0                   5.5   

     Team Tot Yds & TOTO  Team FL  Team 1stD  Team PassingCmp  \
371                 26.0      6.0      233.0            238.0   
657                 33.0     17.0      276.0            288.0   
518                 31.0     14.0      305.0            303.0   
197                 21.0      9.0      269.0            291.0   
5                   31.0     11.0      349.0            394.0   
..                   ...      ...        ...              ...   
85                  25.0      8.0      290.0            306.0   
88                  17.0      4.0      311.0            363.0   
584                 27.0     13.0      277.0            304.0   
145                 30.0     11.0      311.0            355.0   
500                 35.0     13.0      275.0            330.0   

     Team PassingAtt  ...  Def. Rank RushingYds  Def. Rank RushingTD  \
371            488.0  ...                  28.0                 21.0   
657            525.0  ...                  25.0                 10.0   
518            515.0  ...                   2.0                 13.0   
197            514.0  ...                  15.0                  8.0   
5              597.0  ...                  18.0                 21.0   
..               ...  ...                   ...                  ...   
85             496.0  ...                   4.0                  1.0   
88             567.0  ...                  15.0                 16.0   
584            526.0  ...                  24.0                 11.0   
145            619.0  ...                  25.0                 25.0   
500            582.0  ...                  22.0                 30.0   

     Def. Rank RushingY/A  Def. Rank Sc%  Def. Rank TO%  \
371                  25.0           21.0            1.0   
657                  21.0           21.0            7.0   
518                   1.0           11.0           11.0   
197                  16.0            8.0            7.0   
5                    15.0           15.0           32.0   
..                    ...            ...            ...   
85                    4.0            7.0           17.0   
88                   16.0           28.0            1.0   
584                  19.0           12.0           23.0   
145                  23.0           12.0           12.0   
500                   7.0            5.0           29.0   

     Def. Rank Average DriveStart  Def. Rank Average DriveTime  \
371                          25.0                         31.0   
657                          11.0                         20.0   
518                          32.0                         20.0   
197                          28.0                         22.0   
5                            23.0                         29.0   
..                            ...                          ...   
85                           16.0                         17.0   
88                            6.0                          5.0   
584                          22.0                         30.0   
145                          17.0                         12.0   
500        

In [7]:
# Feature Scaling
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# For more see KNN Evaluation Notebook
# KNN Algorithm Evaluation With Neighbors (Lowest Error of .42)
knn = KNeighborsClassifier(n_neighbors=19)
knn.fit(X_train, Y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[31 35]
 [21 47]]
              precision    recall  f1-score   support

           1       0.60      0.47      0.53        66
           2       0.57      0.69      0.63        68

    accuracy                           0.58       134
   macro avg       0.58      0.58      0.58       134
weighted avg       0.58      0.58      0.58       134



In [9]:
# Logistic Regression Evaluation
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[31 35]
 [26 42]]
              precision    recall  f1-score   support

           1       0.54      0.47      0.50        66
           2       0.55      0.62      0.58        68

    accuracy                           0.54       134
   macro avg       0.54      0.54      0.54       134
weighted avg       0.54      0.54      0.54       134



In [10]:
# Logistic Regression Highest Positive Correlations
coeff_df = pd.DataFrame(df.columns.delete(0))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])

coeff_df.sort_values(by='Correlation', ascending=False).head(10)

Feature  Correlation
45              Opp. RushingAtt     0.976711
68          Off. Rank PassingTD     0.962747
11               Team PassingTD     0.859789
57       Opp. Average DriveTime     0.517522
23                     Team #Dr     0.503684
48              Opp. RushingY/A     0.432910
9               Team PassingAtt     0.404799
15              Team RushingAtt     0.395153
101  Def. Rank Average DriveYds     0.365865
85                 Def. Rank FL     0.348869

In [11]:
# Logistic Regression Highest Negative Correlations
coeff_df.sort_values(by='Correlation', ascending=False).tail(10)

Feature  Correlation
72         Off. Rank RushingYds    -0.436855
49             Opp. Rushing1stD    -0.464532
92         Def. Rank RushingAtt    -0.468883
96                Def. Rank Sc%    -0.476333
53                     Opp. #Dr    -0.507871
31                      Opp. PF    -0.567096
99  Def. Rank Average DriveTime    -0.587240
76                Off. Rank TO%    -0.602095
84     Def. Rank Tot Yds & TOTO    -0.647779
63     Off. Rank Tot Yds & TOTO    -0.682048

In [12]:
# SVC Evaluation
svc = SVC()
svc.fit(X_train, Y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[29 37]
 [24 44]]
              precision    recall  f1-score   support

           1       0.55      0.44      0.49        66
           2       0.54      0.65      0.59        68

    accuracy                           0.54       134
   macro avg       0.55      0.54      0.54       134
weighted avg       0.55      0.54      0.54       134



In [13]:
# Gaussian Evaluation
gaussian = GaussianNB()
gaussian.fit(X_train, Y_train)
Y_pred = gaussian.predict(X_test)
acc_gaussian = round(gaussian.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[34 32]
 [27 41]]
              precision    recall  f1-score   support

           1       0.56      0.52      0.54        66
           2       0.56      0.60      0.58        68

    accuracy                           0.56       134
   macro avg       0.56      0.56      0.56       134
weighted avg       0.56      0.56      0.56       134



In [14]:
# Perceptron Evaluation
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
Y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[37 29]
 [35 33]]
              precision    recall  f1-score   support

           1       0.51      0.56      0.54        66
           2       0.53      0.49      0.51        68

    accuracy                           0.52       134
   macro avg       0.52      0.52      0.52       134
weighted avg       0.52      0.52      0.52       134



In [15]:
# Linear SVC Evaluation
linear_svc = LinearSVC(max_iter=10000)
linear_svc.fit(X_train, Y_train)
Y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(linear_svc.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[31 35]
 [28 40]]
              precision    recall  f1-score   support

           1       0.53      0.47      0.50        66
           2       0.53      0.59      0.56        68

    accuracy                           0.53       134
   macro avg       0.53      0.53      0.53       134
weighted avg       0.53      0.53      0.53       134



In [16]:
# SGD Evaluation
sgd = SGDClassifier()
sgd.fit(X_train, Y_train)
Y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[31 35]
 [27 41]]
              precision    recall  f1-score   support

           1       0.53      0.47      0.50        66
           2       0.54      0.60      0.57        68

    accuracy                           0.54       134
   macro avg       0.54      0.54      0.53       134
weighted avg       0.54      0.54      0.54       134



In [17]:
# Decision Tree Evaluation
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[28 38]
 [31 37]]
              precision    recall  f1-score   support

           1       0.47      0.42      0.45        66
           2       0.49      0.54      0.52        68

    accuracy                           0.49       134
   macro avg       0.48      0.48      0.48       134
weighted avg       0.48      0.49      0.48       134



In [18]:
# Random Forest Evaluation
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, Y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, Y_train)
acc_random_forest = round(random_forest.score(X_train, Y_train) * 100, 2)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[27 39]
 [24 44]]
              precision    recall  f1-score   support

           1       0.53      0.41      0.46        66
           2       0.53      0.65      0.58        68

    accuracy                           0.53       134
   macro avg       0.53      0.53      0.52       134
weighted avg       0.53      0.53      0.52       134



In [19]:
# See accuracy on training set
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)

Model   Score
3               Random Forest  100.00
8               Decision Tree  100.00
0     Support Vector Machines   76.17
7                  Linear SVC   69.42
2         Logistic Regression   67.73
1                         KNN   61.16
4                 Naive Bayes   60.79
6  Stochastic Gradient Decent   60.04
5                  Perceptron   57.60